parameters:
  mailer.gmail_user: 'lior@gmail.com'
  mailer.gmail_password: '1234'

services:
  _instanceof: 
    App\HasLoggerInterface:
      tags: ['with_logger']

  _defaults:
    autowire: true
    
  App\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection}"

  App\Controller\OrderController:
    public: true
  
  App\Mailer\MailerInterface:
    alias: App\Mailer\GmailMailer

  App\Texter\TexterInterface:
    alias: App\Texter\SmsTexter

  App\Mailer\GmailMailer:
    arguments:
      - "%mailer.gmail_user%"
      - "%mailer.gmail_password%"  

  App\Texter\SmsTexter:
    arguments:
      $serviceDsn: "send.sms.com"
      $key: "1234Sms"

      
  
